Repository MLH-Fellowship/onboardio, pull requests merged in 2020-09, with the labels that each got.

#1 Add auth screen to house sign in and sign up components
  package.json
  public/index.html
  src/App.js
  src/components/ErrorMessage.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/components/ThemeToggler.js
  src/index.js
  src/pages/LoginForm.js
  yarn.lock
Labels: enhancement

#6 Set up react-router-dom
  package.json
  src/App.js
  src/components/Navbar.js
  src/index.js
  yarn.lock
Labels: enhancement

#5 Add basic api routes for login and register
  .gitignore
  server/.gitignore
  server/api/app.ts
  server/api/controllers/auth.ts
  server/api/middlewares/requestLogger.ts
  server/api/routes/auth.ts
  server/api/services/authService.ts
  server/api/utils/logger.ts
  server/package.json
  server/yarn.lock
Labels: enhancement

#30 Integrated Service Discovery + GitHub Linking
  server/api/app.ts
  server/api/controllers/service.ts
  server/api/interfaces/user.ts
  server/api/middlewares/header.ts
  server/api/routes/service.ts
  server/api/services/service.ts
  server/package-lock.json
  server/package.json
Labels: enhancement

#44 Integrated Discord
  server/api/controllers/service.ts
  server/api/routes/service.ts
  server/api/services/service.ts
Labels: enhancement

#51 Flow Discovery + Fixing Zoom
  server/api/app.ts
  server/api/controllers/flow.ts
  server/api/routes/flow.ts
  server/api/services/flow.ts
  server/api/services/service.ts
Labels: backend

#54 Zoho Linking Integration
  server/api/controllers/service.ts
  server/api/routes/service.ts
  server/api/services/service.ts
Labels: backend

#69 Integrated Asana
  server/api/services/onboard.ts
Labels: backend, enhancement
